### ISSUE TITLE
unable to create sensor

### ISSUE THREAD

**Issue by spiralemystik** [heyajohnny/cryptoinfo#10]
Hi,

Sorry for this dumb question, but i am not able to create any sensors.
Here is my configuration.yaml

`# Crypto sensors
sensor:
  - platform: cryptoinfo
    id: "main wallet"
    cryptocurrency_name: "bitcoin"
    currency_name: "usd"
    multiplier: 1
    update_frequency: 15
    sensors:
      cryptoinfo_main_wallet_bitcoin_usd_24h_market_cap:
        value_template: "{{ state_attr('sensor.cryptoinfo_main_wallet_bitcoin_usd', 'market_cap') | round(0) }}"
        unit_of_measurement: "$"
      cryptoinfo_main_wallet_ripple_usd_24h_market_cap:
        value_template: "{{ state_attr('sensor.cryptoinfo_main_wallet_ripple_usd', 'market_cap') | round(0) }}"
        unit_of_measurement: "$"`

And here is the error when verifying the configuration:
`Invalid config for [sensor.cryptoinfo]: [sensors] is an invalid option for [sensor.cryptoinfo]. Check: sensor.cryptoinfo->sensors. (See ?, line ?). `

**Comment by spiralemystik** [comment]
I managed to split the sensors and sensor.
But now, i am stuck with changing the icon for Ripple

**Comment by heyajohnny** [comment]
I've just added an example [config](https://github.com/heyajohnny/cryptoinfo/blob/master/example/configuration.yaml)
Maybe this can help you out.

But adding icons and stuff is not part of this sensor. You should search for 'Lovelace UI custom icons' or something like that.

**Comment by heyajohnny** [comment]
I'm closing this issue, since I can't help you any further
