### ISSUE TITLE
how to view my own portfolio?

### ISSUE THREAD

**Issue by tung256** [heyajohnny/cryptoinfo#16]
i see configuration to view coins values but how do i actually view my own portfolio that's in coingecko.com?
basically, it would be nice to see a tab in HA such as my holdings
BTC  total values= $70,000
ETH total values= $89,000
===============
total values=        $159,000

your configuration files is so simple. could you please elaborate on how to set up everything as seen in the example above?

**Comment by tung256** [comment]
sorry i dont know why some letters are bolded in the above.

**Comment by heyajohnny** [comment]
It's not possible 'yet'. When I made this sensor, CoinGecko didn't have any portfolio tracker. I'll take a look at it soon.

**Comment by heyajohnny** [comment]
As far as I can see, it's not possible to use the CoinGecko Portfolio tracker through the CoinGecko [API](https://www.coingecko.com/nl/api/documentation). I'm sorry
