### ISSUE TITLE
adding 1hr, 7d, and 30d function

### ISSUE THREAD

**Issue by clm302002** [heyajohnny/cryptoinfo#28]
Hey man i aboslutely love this addon.  been using it a ton for all my crypto.  it works amazing and havent had a minutes worth of trouble.  would just like to request if possible to have it also pull the data for 1hr, 7d, and 30d.  thanks a bunch

**Comment by heyajohnny** [comment]
Sorry for the wait. I've just published a new version with the following changes:
-Added 1h, 24h, 7d, 30d volume + circulating and total supply attributes

Please let me know if all works as expected
