### ISSUE TITLE
not working...

### ISSUE THREAD

**Issue by Dario82** [heyajohnny/cryptoinfo#29]
Logger: homeassistant.helpers.entity
Source: custom_components/cryptoinfo/sensor.py:137
Integration: cryptoinfo ([documentation](https://github.com/heyajohnny/cryptoinfo))
First occurred: 09:28:05 (933 occurrences)
Last logged: 12:03:06

I receive this in log:
`
<div class="cf-section cf-wrapper">
    <div class="cf-columns two">
      <div class="cf-column">
        <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
        
        <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
      </div>

      <div class="cf-column">
        <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
        

        <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

        <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
        
          
        
      </div>
    </div>
`

**Comment by heyajohnny** [comment]
Strange... Never seen this warning / error. Maybe some antivirus that is running on your Home Assistant machine is responsible for this.
