### ISSUE TITLE
Crypto MUNT not found

### ISSUE THREAD

**Issue by embezon** [heyajohnny/cryptoinfo#33]
Using this cryptoinfo with MUNT, it's not found.

configuration.yaml:
# cryptoinfo / cryptogecko
  - platform: cryptoinfo
    id: "btc"         
    cryptocurrency_name: "bitcoin" 
    currency_name: "eur"          
    unit_of_measurement: "\u200b"  
    multiplier: 1             
    update_frequency: 15
  - platform: cryptoinfo
    id: "eth"         
    cryptocurrency_name: "ethereum" 
    currency_name: "eur"          
    unit_of_measurement: "\u200b"  
    multiplier: 1             
    update_frequency: 15
  - platform: cryptoinfo
    id: "munt"         
    cryptocurrency_name: "munt" 
    currency_name: "eur"          
    unit_of_measurement: "\u200b"  
    multiplier: 1             
    update_frequency: 15 
  - platform: cryptoinfo
    id: "xfl"         
    cryptocurrency_name: "florin" 
    currency_name: "eur"          
    unit_of_measurement: "\u200b"  
    multiplier: 1             
    update_frequency: 15

Result after restart:
For every coin it gives the price, except for munt.  'UnKnown'

**Comment by heyajohnny** [comment]
Do you mean this one?
{"id":"gulden","symbol":"munt","name":"Munt"}
If so, then try using 'gulden' instead of 'munt'.

**Comment by embezon** [comment]
It's a little bit odd, but that's the trick indeed. Thanks.

Is it possible to change the symbols of every coin. All 4 shows now the BTC icon......

**Comment by heyajohnny** [comment]
Changing the 'unit_of_measurement' should fix that
