### ISSUE TITLE
Update frequency in seconds

### ISSUE THREAD

**Issue by TheHolyRoger** [heyajohnny/cryptoinfo#34]
Would be nice to have the option of smaller update intervals than 1 minute :)

**Comment by heyajohnny** [comment]
Just updated the code to accept floating point values.
you can now use for example 0.1 as update interval, so it updates every 6 seconds.
Beware of the limitations of CoinGecko.
![image](https://user-images.githubusercontent.com/20553716/227261303-026abe95-9e98-4d3d-b142-bf81c39c86ab.png)

**Comment by TheHolyRoger** [comment]
Amazing thank you

**Comment by TheHolyRoger** [comment]
Works great, my lights flash much more often :D
