### ISSUE TITLE
Sensor Reporting Unknown

### ISSUE THREAD

**Issue by yjamal01** [heyajohnny/cryptoinfo#37]
Seems like my sensors are reporting unknown for BTC. I tried to rollback using a backup and then tried to uninstall/reinstall via HACS but still the same issue. 

`sensor:
  - platform: cryptoinfo
    id: "main wallet"
    cryptocurrency_name: "bitcoin"
    currency_name: "cad"
    multiplier: 1
    update_frequency: 1
  
  - platform: template
    sensors:
      cryptoinfo_main_wallet_bitcoin_cad_24h_volume:
        value_template: "{{ state_attr('sensor.cryptoinfo_main_wallet_bitcoin_cad', 'volume') | round(0) }}"
        unit_of_measurement: "$"`

**Comment by Largus72** [comment]
Same here.
My sensor is giving a flat-line with the last bitcoin value of yesterday 13:00.

**Comment by checkiecheck** [comment]
yeah.. was playing a lot with HA lately and spotted this too yesterday. Seems API response is invalid for the integration, while the API v3 seemed to work in a  browser.
Dont get it, but possibly some url changes on coingecko

**Comment by heyajohnny** [comment]
Yes, the CoinGecko API is broken. Let's hope they'll fix it soon

**Comment by heyajohnny** [comment]
Looks like it's working again... Hope it stays on.
