### ISSUE TITLE
seperate sensor for 24h change attribute

### ISSUE THREAD

**Issue by jboesh** [heyajohnny/cryptoinfo#38]
Hi, I want to create a seperate sensor for the 24h change attribute, do you have a template example?
Thanks for this addition!

**Comment by heyajohnny** [comment]
There's an example with the 24h_volume attribute in the [README](https://github.com/heyajohnny/cryptoinfo) . Just change the '24h_volume' into '24h_change' and it should work. (Also change the name of the 'sensor.xxx' According to the name of your sensor)
