### ISSUE TITLE
cannot track Horizen crypto

### ISSUE THREAD

**Issue by foegra** [heyajohnny/cryptoinfo#43]
it's interesting, but Horizen crypto has no ID field on coingecko API.
Is it possible to walk around this?

**Comment by heyajohnny** [comment]
Do you mean this Horizen?
` {
        "id": "zencash",
        "symbol": "zen",
        "name": "Horizen"
},`

**Comment by foegra** [comment]
That is correct, I was searching it wrongly. Sorry for that.

**Comment by foegra** [comment]
Not an issue
