### ISSUE TITLE
feature request: poll distribution

### ISSUE THREAD

**Issue by h8hr1pzdo3rmiqv5** [heyajohnny/cryptoinfo#48]
Problem encountered: I want to track a lot of coins (say, 60), and only need a daily update. I could poll the CoinGecko API once every minute during 60 minutes, which would meet their API rates.
However, the current version of CryptoInfo sends a poll for every coin at once when starting, then will poll according to update_frequency.

Possibles ways to resolve this:
• poll queue: set an extension-wide variable (minutes between each poll, for example), which would serve to queue the sensor updates if the rate has been reached;
• poll hour: on a sensor level, instead of update_frequency, have the possibility of setting update_schedule, which would let the user set when exactly the poll has to be sent (crontab-like, for example).

Thank you.

**Comment by heyajohnny** [comment]
I'll see what i can do
I first need to refactor some code and probably can add this feature while doing the refactor.
I'll let you know when I'm starting on this

**Comment by heyajohnny** [comment]
I've made a beginning with the code update. I'll let you know when I've got something usefull

**Comment by heyajohnny** [comment]
I've just released a new version. Please let me know if this fixes your problem. 

You can now use multiple cryptocurrencies in 1 sensor. This has the advantage that only 1 request goes to the Coingecko API that updates the values ​​of the multiple cryptocurrencies. 
Also a property has been added to set the minimum request time between multiple sensors

**Comment by h8hr1pzdo3rmiqv5** [comment]
Hello,
big refactor indeed! Thank you. It seem to solve that issue in particular.
