### ISSUE TITLE
Récupération de la valeur 

### ISSUE THREAD

**Issue by kweebix** [heyajohnny/cryptoinfo#5]
Bonjour j'aimerais savoir si il est possible de récupérer la valeur pour la multiplier par le nombre exact que l'on a pour avec la valeur de notre porte monnaie

Exemple j'ai 0.25 de bitcoin j'aimerais afficher la veul en euro

**Comment by heyajohnny** [comment]
Bonjour,
I've just pushed a new version in which you can use a 'multiplier'. I hope this fixes your issue ;)

**Comment by kweebix** [comment]
really nice thx
