### ISSUE TITLE
Include token symbol and name in attributes

### ISSUE THREAD

**Issue by bakman2** [heyajohnny/cryptoinfo#51]
I want to be able to use a list of token and loop through it and render, ie.:

```
{%set tokens = [sensor.cryptoinfo_tokens_ethereum_eur,sensor.cryptoinfo_tokens_bitcoin_eur] %}
```
But as there is no actual name/symbol/description of the token itself in the attributes, it makes it cumbersome to directly render something like;

BTC (Bitcoin)
ETH (Ethereum)

**Comment by heyajohnny** [comment]
I've just published an update, but it will break your current sensors. Please remove and re-add the sensors

Version: 1.0.2 20241121 - Added cryptocurrency_id, cryptocurrency_name, cryptocurrency_symbol and currency_name to attributes

**Comment by bakman2** [comment]
Thanks a lot man!

<img width="565" alt="image" src="https://github.com/user-attachments/assets/c32c9a35-6ebb-4993-aa2a-dd537d7edb80">

easy to populate a ticker :)

**Comment by bakman2** [comment]
Looks good to me
