### ISSUE TITLE
feat: add tracking of 1 year changes

### ISSUE THREAD

**Issue by th3cube** [heyajohnny/cryptoinfo#54]
Can you also add the tacking for 1y and 14d changes ?
![image](https://github.com/user-attachments/assets/d744dde3-03e6-42ad-8881-e79e8aaf7fdb)

the other attributes are all available.

![image](https://github.com/user-attachments/assets/1e79446c-f495-4617-b01a-5cdb0a989971)

Thank you for this Great Integration btw.

**Comment by heyajohnny** [comment]
I've just added the 14 day change and 1 year change in v1.0.6. Please let me know if all works as expected

**Comment by th3cube** [comment]
Thank You for the fast Adjustment! It works great.

I use your Integration for displaying a live ticket on an dot matrix display with Awtrix 

![awtrix-2](https://github.com/user-attachments/assets/650b69a5-2605-414c-9c5e-2d9398bf0712)


I wrote a HA Blueprint for it and will link your repository in the BP description, if you don’t mind, as it’s necessary for retrieving all the data. I will also submit the blueprint to the Awtrix community to have it listed on their site.

Thanks for This!

**Comment by heyajohnny** [comment]
@th3cube Ow wow! That's looks pretty cool. 
Of course you may link my repository. I'm already glad that people are actually using my stuff :smiley:
